version: '3.8'

services:
  db:
    build:
      context: ./db
      dockerfile: dockerfile
    container_name: coletron_db
    restart: always
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: coletron
      MYSQL_USER: user
      MYSQL_PASSWORD: senha

  app:
    build: ./app
    container_name: coletron_app
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    stdin_open: true # Adicionado
    tty: true # Adicionado

volumes:
  db_data:
